num_layers: 4
input_dim: 256
hidden_dim: 128
output_dim: 20
activation: 'relu'
loss_fn: 'mse'
optimizer: 'sgd'
learning_rate: 0.0001
max_epochs: 20
max_hidden: 10
batch_size: 64
num_workers: 8
dataset_path: 'new_data'
log_dir: 'new_logs'
log_level: 'debug'
log_interval: 20