model_type: 'two_layer'
num_layers: 2
input_dim: 784
hidden_dim: 1
output_dim: 10
activation: 'relu'
loss_fn: 'cross_entropy'
optimizer: 'sgd'
learning_rate: 0.001
max_epochs: 20
min_hidden: 1
max_hidden: 10
batch_size: 64
num_workers: 8
log_dir: 'logs'
log_interval: 20
device: 'cuda'
dataset: 'mnist'